In [1]:
!pip install faker

Collecting faker
  Downloading faker-40.8.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: tzdata in d:\e-commerce\.venv\lib\site-packages (from faker) (2025.3)
Downloading faker-40.8.0-py3-none-any.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ---------- ----------------------------- 0.5/2.0 MB 1.9 MB/s eta 0:00:01
   --------------------- ------------------ 1.0/2.0 MB 1.9 MB/s eta 0:00:01
   -------------------------- ------------- 1.3/2.0 MB 1.9 MB/s eta 0:00:01
   ------------------------------------ --- 1.8/2.0 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 2.0/2.0 MB 1.8 MB/s  0:00:01
Installing collected packages: faker
Successfully installed faker-40.8.0

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
import numpy as np
from faker import Faker
import random
fake = Faker()

## products dim

In [2]:
products = pd.read_csv("D:/E-commerce/Data/raw/olist_products_dataset.csv")

In [3]:
products.head()

,product_id,products_english,product_name_lenght,product_description_lenght
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumery,40.0,287.0
1,3aa071139cb16b67ca9e5dea641aaa2f,art,44.0,276.0
2,96bd76ec8810374ed1b65e291975717f,sports_leisure,46.0,250.0
3,cef67bcfe19066a932b7673e239eb23d,baby,27.0,261.0
4,9dc1a7de274444849c219cff195d0b71,housewares,37.0,402.0

In [4]:
products['products_english'].value_counts()

products_english
bed_bath_table               3029
sports_leisure               2867
furniture_decor              2657
health_beauty                2444
housewares                   2335
                             ...
tablets_printing_image          9
fashion_childrens_clothes       5
home_comfort_2                  5
security_and_services           2
cds_dvds_musicals               1
Name: count, Length: 72, dtype: int64

In [5]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   products_english            32951 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
dtypes: float64(2), str(2)
memory usage: 1.0 MB

In [6]:
products.rename(columns={"products_english": "product_category"}, inplace=True)

In [7]:
brands = [fake.company() for _ in range(40)]

# create fake columns
products["brand"] = [random.choice(brands) for _ in range(len(products))]

In [8]:
print(products.columns)

Index(['product_id', 'product_category', 'product_name_lenght',
       'product_description_lenght', 'brand'],
      dtype='str')

In [9]:
products["product_category"] = products["product_category"].str.lower()

In [10]:
products['product_name']=products['brand']+" "+products['product_category'].str.replace("_", " ").str.title()

In [11]:
products.tail()

,product_id,product_category,product_name_lenght,product_description_lenght,brand,product_name
32946,a0b7d5a992ccda646f2d34e418fff5a0,furniture_decor,45.0,67.0,Fletcher-Mathis,Fletcher-Mathis Furniture Decor
32947,bf4538d88321d0fd4412a93c974510e6,construction_tools_lights,41.0,971.0,"Pope, Wheeler and Greer","Pope, Wheeler and Greer Construction Tools Lights"
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,bed_bath_table,50.0,799.0,"Lewis, Baker and Gonzales","Lewis, Baker and Gonzales Bed Bath Table"
32949,83808703fc0706a22e264b9d75f04a2e,computers_accessories,60.0,156.0,Hart PLC,Hart PLC Computers Accessories
32950,106392145fca363410d287a815be6de4,bed_bath_table,58.0,309.0,Jones-Gonzalez,Jones-Gonzalez Bed Bath Table

In [12]:
products.duplicated().sum()

np.int64(0)

In [13]:
products.isnull().sum()

product_id                      0
product_category                0
product_name_lenght           610
product_description_lenght    610
brand                           0
product_name                    0
dtype: int64

In [14]:
products['product_key']=range(1, len(products) + 1)

In [15]:
products.drop(columns=["product_name_lenght","product_description_lenght"], inplace=True)

In [20]:
products.to_csv("products_processed.csv", index=False)

## Customers Dim

In [16]:
customers = pd.read_csv("D:/E-commerce/Data/raw/olist_customers_dataset.csv")

In [17]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [18]:
customers.duplicated().sum()
customers.isnull().sum()
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [7]:
!pip install unidecode

Requirement already satisfied: unidecode in d:\e-commerce\.venv\lib\site-packages (1.4.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [19]:
import unidecode

customers['customer_city_english'] = customers['customer_city'].apply(lambda x: unidecode.unidecode(x))

In [20]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,customer_city_english
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,franca
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,sao bernardo do campo
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,sao paulo
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,mogi das cruzes
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,campinas

In [21]:
customers.drop(columns=["customer_city"], inplace=True)

In [22]:
customers["gender"] = [random.choice(["M", "F"]) for _ in range(len(customers))]

In [23]:
age_groups = ["18-25", "26-35", "36-45", "46-55", "56+"]
customers["age_group"] = [random.choice(age_groups) for _ in range(len(customers))]

In [24]:
start_date = pd.to_datetime('01-01-2015')
end_date = pd.to_datetime('31-12-2017')

customers['registration_date'] =[fake.date_between(start_date=start_date,end_date=end_date) for _ in range(len(customers))]
customers['registration_date'] = pd.to_datetime(customers['registration_date'])
customers['registration_date'].dt.strftime('%Y-%m-%d')

C:\Users\TUF\AppData\Local\Temp\ipykernel_36248\3052111993.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  end_date = pd.to_datetime('31-12-2017')

0        2016-09-14
1        2015-07-26
2        2015-05-23
3        2015-06-12
4        2016-02-11
            ...
99436    2016-03-18
99437    2016-10-15
99438    2017-11-25
99439    2017-06-16
99440    2015-12-17
Name: registration_date, Length: 99441, dtype: str

In [25]:
customers['customer_key']=range(1, len(customers) + 1)

In [26]:
customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_state,customer_city_english,gender,age_group,registration_date,customer_key
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,SP,franca,F,56+,2016-09-14,1
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,SP,sao bernardo do campo,M,26-35,2015-07-26,2
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,SP,sao paulo,F,56+,2015-05-23,3
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,SP,mogi das cruzes,F,56+,2015-06-12,4
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,SP,campinas,M,18-25,2016-02-11,5
...,...,...,...,...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,SP,sao paulo,M,18-25,2016-03-18,99437
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,SP,taboao da serra,M,56+,2016-10-15,99438
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,CE,fortaleza,F,36-45,2017-11-25,99439
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,RS,canoas,M,18-25,2017-06-16,99440
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,SP,cotia,F,26-35,2015-12-17,99441

In [27]:
customers['registration_date'].value_counts()

registration_date
2017-07-11    128
2015-10-07    127
2017-07-06    123
2016-03-05    119
2017-02-19    119
             ...
2015-11-16     67
2015-10-22     67
2017-11-20     66
2015-07-07     66
2016-02-28     64
Name: count, Length: 1095, dtype: int64

In [28]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_state            99441 non-null  str
 4   customer_city_english     99441 non-null  str
 5   gender                    99441 non-null  str
 6   age_group                 99441 non-null  str
 7   registration_date         99441 non-null  datetime64[s]
 8   customer_key              99441 non-null  int64
dtypes: datetime64[s](1), int64(2), str(6)
memory usage: 6.8 MB

In [18]:
customers.to_csv("customers_processed.csv", index=False)

## Payment dim

In [29]:
paymentrw=pd.read_csv("D:/E-commerce/Data/raw/olist_order_payments_dataset.csv")

In [30]:
payment = paymentrw[['payment_type']].drop_duplicates().reset_index(drop=True)
payment['payment_key'] = payment.index + 1

In [31]:
payment["payment_key"]=range(1,len(payment)+1)

In [32]:
payment

  payment_type  payment_key
0  credit_card            1
1       boleto            2
2      voucher            3
3   debit_card            4
4  not_defined            5

In [140]:
payment.to_csv("payment_processed.csv", index=False)

## shipping dim

In [33]:
shipping=pd.read_csv("D:/E-commerce/Data/raw/olist_orders_dataset.csv")
orders=pd.read_csv("D:/E-commerce/Data/raw/olist_order_items_dataset.csv")

In [34]:
shipping

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,10/2/2017 10:56,10/2/2017 11:07,10/4/2017 19:55,10/10/2017 21:25,10/18/2017 0:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,7/24/2018 20:41,7/26/2018 3:24,7/26/2018 14:31,8/7/2018 15:27,8/13/2018 0:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,8/8/2018 8:38,8/8/2018 8:55,8/8/2018 13:50,8/17/2018 18:06,9/4/2018 0:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,11/18/2017 19:28,11/18/2017 19:45,11/22/2017 13:39,12/2/2017 0:28,12/15/2017 0:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2/13/2018 21:18,2/13/2018 22:20,2/14/2018 19:46,2/16/2018 18:17,2/26/2018 0:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,3/9/2017 9:54,3/9/2017 9:54,3/10/2017 11:18,3/17/2017 15:08,3/28/2017 0:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2/6/2018 12:58,2/6/2018 13:10,2/7/2018 23:22,2/28/2018 17:37,3/2/2018 0:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,8/27/2017 14:46,8/27/2017 15:04,8/28/2017 20:52,9/21/2017 11:24,9/27/2017 0:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,1/8/2018 21:28,1/8/2018 21:36,1/12/2018 15:35,1/25/2018 23:32,2/15/2018 0:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,3/8/2018 20:57,3/9/2018 11:20,3/9/2018 22:11,3/16/2018 13:08,4/3/2018 0:00

In [35]:
shipping["shipping_key"]=range(1,len(shipping)+1)

In [36]:
shipping["shipping_type"]=orders["freight_value"].apply(lambda x: "Express" if x > 50 else "Standard")

In [37]:
shipping['delivery_days'] = (pd.to_datetime(shipping['order_estimated_delivery_date'])-pd.to_datetime(shipping['order_purchase_timestamp'])).dt.days

In [38]:
shipping

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,shipping_key,shipping_type,delivery_days
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,10/2/2017 10:56,10/2/2017 11:07,10/4/2017 19:55,10/10/2017 21:25,10/18/2017 0:00,1,Standard,15
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,7/24/2018 20:41,7/26/2018 3:24,7/26/2018 14:31,8/7/2018 15:27,8/13/2018 0:00,2,Standard,19
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,8/8/2018 8:38,8/8/2018 8:55,8/8/2018 13:50,8/17/2018 18:06,9/4/2018 0:00,3,Standard,26
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,11/18/2017 19:28,11/18/2017 19:45,11/22/2017 13:39,12/2/2017 0:28,12/15/2017 0:00,4,Standard,26
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2/13/2018 21:18,2/13/2018 22:20,2/14/2018 19:46,2/16/2018 18:17,2/26/2018 0:00,5,Standard,12
...,...,...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,3/9/2017 9:54,3/9/2017 9:54,3/10/2017 11:18,3/17/2017 15:08,3/28/2017 0:00,99437,Express,18
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2/6/2018 12:58,2/6/2018 13:10,2/7/2018 23:22,2/28/2018 17:37,3/2/2018 0:00,99438,Standard,23
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,8/27/2017 14:46,8/27/2017 15:04,8/28/2017 20:52,9/21/2017 11:24,9/27/2017 0:00,99439,Standard,30
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,1/8/2018 21:28,1/8/2018 21:36,1/12/2018 15:35,1/25/2018 23:32,2/15/2018 0:00,99440,Standard,37
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,3/8/2018 20:57,3/9/2018 11:20,3/9/2018 22:11,3/16/2018 13:08,4/3/2018 0:00,99441,Standard,25

In [39]:
shipping.drop(columns=["order_approved_at","order_delivered_carrier_date","order_delivered_customer_date","order_estimated_delivery_date"], inplace=True)

In [40]:
shipping

,order_id,customer_id,order_status,order_purchase_timestamp,shipping_key,shipping_type,delivery_days
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,10/2/2017 10:56,1,Standard,15
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,7/24/2018 20:41,2,Standard,19
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,8/8/2018 8:38,3,Standard,26
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,11/18/2017 19:28,4,Standard,26
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2/13/2018 21:18,5,Standard,12
...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,3/9/2017 9:54,99437,Express,18
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2/6/2018 12:58,99438,Standard,23
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,8/27/2017 14:46,99439,Standard,30
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,1/8/2018 21:28,99440,Standard,37
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,3/8/2018 20:57,99441,Standard,25

In [46]:
shipping.to_csv("shipping_processed.csv", index=False)

## Date dim

In [41]:
date_range = pd.date_range(start='2015-01-01', end='2018-12-31', freq='D')

date=pd.DataFrame({
    "full_date": date_range
})

In [42]:
date

      full_date
0    2015-01-01
1    2015-01-02
2    2015-01-03
3    2015-01-04
4    2015-01-05
...         ...
1456 2018-12-27
1457 2018-12-28
1458 2018-12-29
1459 2018-12-30
1460 2018-12-31

[1461 rows x 1 columns]

In [43]:
date['date_key']=date['full_date'].dt.strftime('%Y%m%d').astype(str).str.replace("-","").str.replace("/","")
date['day_of_week'] = date['full_date'].dt.day_name()
date['month'] = date['full_date'].dt.month
date['year'] = date['full_date'].dt.year
date['month_name'] = date['full_date'].dt.month_name()
date['quarter'] = date['full_date'].dt.quarter
date['week_of_year'] = date['full_date'].dt.isocalendar().week
date['day']=date['full_date'].dt.day_of_week

In [ ]:
date.to_csv("date_processed.csv", index=False)

## Category Dim

In [44]:
filtered_categories = []
special_cases = ['la_cuisine', 'small_appliances_home_oven_and_coffee', 'home_comfort_ventilation_and_cooling',
                 "home_comfort_heating_and_cooling","fixed_telephony",
                 "small_appliances","cool_stuff",'air_conditioning',
                 "market_place","cine_photo"
                 ]
for name in products['product_category']:
    name=name.strip().lower()
    if "_" not in name or name in special_cases:
        filtered_categories.append(name.title())
    else:
        category = name.split("_")[0].title()
        filtered_categories.append(category)

category=pd.DataFrame({
    "category_key": range(1, len(products) + 1),
    "seasonal_flag": [random.choice([0, 1]) for _ in range(len(products))],
    "product_category": products['product_category'],
    "parent_category": filtered_categories
})

In [45]:
most_frequent = category['parent_category'].mode()[0]
category['parent_category'] = category['parent_category'].replace(
    ["Not Found", "not found"], most_frequent
)
category['parent_category'] = category['parent_category'].replace(
    "Fashio","Fashion"
)

In [46]:
category

       category_key  seasonal_flag           product_category parent_category
0                 1              1                  perfumery       Perfumery
1                 2              0                        art             Art
2                 3              1             sports_leisure          Sports
3                 4              0                       baby            Baby
4                 5              0                 housewares      Housewares
...             ...            ...                        ...             ...
32946         32947              1            furniture_decor       Furniture
32947         32948              0  construction_tools_lights    Construction
32948         32949              1             bed_bath_table             Bed
32949         32950              0      computers_accessories       Computers
32950         32951              1             bed_bath_table             Bed

[32951 rows x 4 columns]

In [47]:
category["parent_category"].value_counts().index

Index(['Bed', 'Furniture', 'Sports', 'Health', 'Housewares', 'Auto',
       'Computers', 'Toys', 'Watches', 'Fashion', 'Telephony', 'Baby',
       'Perfumery', 'Stationery', 'Home', 'Cool_Stuff', 'Garden', 'Pet',
       'Construction', 'Electronics', 'Books', 'Luggage', 'Consoles', 'Office',
       'Musical', 'Small_Appliances', 'Food', 'Costruction',
       'Air_Conditioning', 'Fixed_Telephony', 'Market_Place', 'Kitchen',
       'Signaling', 'Drinks', 'Agro', 'Industry', 'Christmas', 'Audio', 'Art',
       'Dvds', 'Small_Appliances_Home_Oven_And_Coffee', 'Cine_Photo', 'Music',
       'Party', 'Arts', 'Flowers', 'Diapers', 'La_Cuisine', 'Tablets',
       'Security', 'Cds'],
      dtype='str', name='parent_category')

In [48]:
category.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   category_key      32951 non-null  int64
 1   seasonal_flag     32951 non-null  int64
 2   product_category  32951 non-null  str
 3   parent_category   32951 non-null  str
dtypes: int64(2), str(2)
memory usage: 1.0 MB

In [49]:
category

       category_key  seasonal_flag           product_category parent_category
0                 1              1                  perfumery       Perfumery
1                 2              0                        art             Art
2                 3              1             sports_leisure          Sports
3                 4              0                       baby            Baby
4                 5              0                 housewares      Housewares
...             ...            ...                        ...             ...
32946         32947              1            furniture_decor       Furniture
32947         32948              0  construction_tools_lights    Construction
32948         32949              1             bed_bath_table             Bed
32949         32950              0      computers_accessories       Computers
32950         32951              1             bed_bath_table             Bed

[32951 rows x 4 columns]

In [49]:
category.to_csv("category_processed.csv", index=False)

## Orders Table

In [3]:
orders = pd.read_csv("D:/E-commerce/Data/raw/olist_orders_dataset.csv")
orders_2=pd.read_csv("D:/E-commerce/Data/raw/olist_order_items_dataset.csv")

In [51]:
fact = orders_2.merge(
    orders[['order_id','customer_id','order_purchase_timestamp']],
    on='order_id',
    how='left'
)

In [52]:
fact.shape

(112650, 9)

In [53]:
payments_agg = paymentrw.groupby('order_id').agg(
    payment_type=('payment_type','first'),  # or choose main payment type
    payment_value=('payment_value','sum')
).reset_index()

fact = fact.merge(payments_agg, on='order_id', how='left')

In [54]:
payment_dim = payment[['payment_type']].drop_duplicates().reset_index(drop=True)
payment_dim['payment_key'] = payment_dim.index + 1

fact['payment_key'] = fact['payment_type'].map(
    dict(zip(payment_dim['payment_type'], payment_dim['payment_key']))
)

In [55]:
# Merge product info first
fact = fact.merge(
    products[['product_id','product_category']],
    on='product_id',
    how='left'
)

# Now map the category key
fact['category_key'] = fact['product_category'].map(
    dict(zip(category['product_category'], category['category_key']))
)

In [56]:
# Category
fact['category_key'] = fact['product_category'].map(
    dict(zip(category['product_category'], category['category_key']))
)

# Product
fact['product_key'] = fact['product_id'].map(
    dict(zip(products['product_id'], products['product_key']))
)

# Customer
fact['customer_key'] = fact['customer_id'].map(
    dict(zip(customers['customer_id'], customers['customer_key']))
)

# Shipping
fact['shipping_key'] = fact['order_id'].map(
    dict(zip(shipping['order_id'], shipping['shipping_key']))
)

In [57]:
fact['order_purchase_timestamp'] = pd.to_datetime(fact['order_purchase_timestamp'])
fact['order_date'] = fact['order_purchase_timestamp'].dt.normalize()
fact['order_purchase_timestamp']=fact['order_purchase_timestamp'].dt.strftime('%Y-%m-%d' )

date_map = dict(zip(date['full_date'], date['date_key']))
fact['date_key'] = fact['order_date'].map(date_map)

fact = fact.drop(columns=['order_date'])

In [58]:
fact['order_purchase_timestamp'].info()

<class 'pandas.Series'>
RangeIndex: 112650 entries, 0 to 112649
Series name: order_purchase_timestamp
Non-Null Count   Dtype
--------------   -----
112650 non-null  str
dtypes: str(1)
memory usage: 880.2 KB

In [59]:
fact.shape

(112650, 18)

In [60]:
fact

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_purchase_timestamp,payment_type,payment_value,payment_key,product_category,category_key,product_key,customer_key,shipping_key,date_key
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,2017-09-13,credit_card,72.19,1.0,cool_stuff,32932,25866,65558,85268,20170913
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,2017-04-26,credit_card,259.83,1.0,pet_shop,32910,27231,34266,71854,20170426
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,2018-01-14,credit_card,216.87,1.0,furniture_decor,32947,22625,34956,6299,20180114
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,2018-08-08,credit_card,25.78,1.0,perfumery,32921,15404,51764,22551,20180808
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,2017-02-04,credit_card,218.04,1.0,garden_tools,32926,8863,7603,5248,20170204
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,b51593916b4b8e0d6f66f2ae24f2673d,2018-04-23,boleto,343.40,2.0,housewares,32946,4738,88326,79551,20180423
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,84c5d4fbaf120aae381fad077416eaa0,2018-07-14,boleto,386.53,2.0,computers_accessories,32950,9256,26678,70156,20180714
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,29309aa813182aaddc9b259e31b870e6,2017-10-23,credit_card,116.85,1.0,sports_leisure,32940,24016,1508,52700,20171023
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,b5e6afd5a41800fdf401e0272ca74655,2017-08-14,credit_card,64.71,1.0,computers_accessories,32950,22356,56645,59872,20170814
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,96d649da0cc4ff33bb408b199d4c7dcf,2018-06-09,credit_card,55.79,1.0,bed_bath_table,32951,5901,3881,59742,20180609

In [61]:
fact['quantity'] = fact.groupby(['order_id','product_id'])['order_item_id'].transform('count')

In [62]:
fact['quantity'].value_counts().index

Index([1, 2, 3, 4, 6, 5, 10, 20, 15, 7, 14, 12, 9, 8, 13, 11], dtype='int64', name='quantity')

In [63]:
fact['gross_amount'] = fact['quantity'] * fact['price']

In [64]:
np.random.seed(42)
fact['discount_amount'] = (fact['gross_amount'] * 
                               np.random.uniform(0, 0.2, len(fact))).round(2)

# Step 4: Derive remaining measures
fact['net_amount'] = fact['gross_amount'] - fact['discount_amount']

# Simulate cost (e.g. 60% of net as COGS)
fact['cost_amount'] = (fact['net_amount'] * np.random.uniform(0.5,0.8)).round(2)
fact['profit_amount'] = round(fact['net_amount'] - fact['cost_amount'], 2)

In [65]:
fact

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_purchase_timestamp,payment_type,...,product_key,customer_key,shipping_key,date_key,quantity,gross_amount,discount_amount,net_amount,cost_amount,profit_amount
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,2017-09-13,credit_card,...,25866,65558,85268,20170913,1,58.90,4.41,54.49,38.60,15.89
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,2017-04-26,credit_card,...,27231,34266,71854,20170426,1,239.90,45.62,194.28,137.63,56.65
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,2018-01-14,credit_card,...,22625,34956,6299,20180114,1,199.00,29.13,169.87,120.34,49.53
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,2018-08-08,credit_card,...,15404,51764,22551,20180808,1,12.99,1.56,11.43,8.10,3.33
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,2017-02-04,credit_card,...,8863,7603,5248,20170204,1,199.90,6.24,193.66,137.19,56.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,b51593916b4b8e0d6f66f2ae24f2673d,2018-04-23,boleto,...,4738,88326,79551,20180423,1,299.99,15.88,284.11,201.27,82.84
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,84c5d4fbaf120aae381fad077416eaa0,2018-07-14,boleto,...,9256,26678,70156,20180714,1,350.00,65.68,284.32,201.41,82.91
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,29309aa813182aaddc9b259e31b870e6,2017-10-23,credit_card,...,24016,1508,52700,20171023,1,99.90,9.06,90.84,64.35,26.49
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,b5e6afd5a41800fdf401e0272ca74655,2017-08-14,credit_card,...,22356,56645,59872,20170814,1,55.99,1.70,54.29,38.46,15.83
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,96d649da0cc4ff33bb408b199d4c7dcf,2018-06-09,credit_card,...,5901,3881,59742,20180609,1,43.00,6.34,36.66,25.97,10.69

In [66]:
fact.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'customer_id',
       'order_purchase_timestamp', 'payment_type', 'payment_value',
       'payment_key', 'product_category', 'category_key', 'product_key',
       'customer_key', 'shipping_key', 'date_key', 'quantity', 'gross_amount',
       'discount_amount', 'net_amount', 'cost_amount', 'profit_amount'],
      dtype='str')

In [67]:
fact['order_id'].nunique()==len(fact)

False

In [68]:
fact_orders = fact[[
    "order_id",
    "customer_key",
    "product_key",
    "date_key",
    "shipping_key",
    "payment_key",
    "category_key",
    "quantity",
    "gross_amount",
    "discount_amount",
    "net_amount",
    "cost_amount",
    "profit_amount"
]]

fact_orders.to_csv("Fact_Order_Line.csv", index=False)

In [69]:
fact.duplicated().sum()

np.int64(0)